# Generated by Django 4.2.1 on 2023-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='item',
            name='unique_code',
            field=models.CharField(default=0, max_length=32, unique=True),
        ),
    ]
